---
horizon:
  keystone_api_version: 3
  session_timeout: 5400
  customize: false
  horizon_lib_dir: "/opt/openstack/current/horizon"
  rhel_lib_dir: "/usr/share/openstack-dashboard"
  nextgen_instance_panel: true
  legacy_instance_panel: false
  session_engine: django.contrib.sessions.backends.cache
  password_validator:
    enabled: True
    regex:  '^(?=.*\d)(?=.*[a-z]).{8,}$'
    help_text: 'Password is not compliant. Password must contain lowercase letters, digits, and be at least 8 characters in length.'
  distro:
    project_packages:
      - openstack-dashboard
    python_post_dependencies: []
  source:
    python_post_dependencies: []
    rev: 'stable/newton'
    constrain: True
    upper_constraints: 'https://raw.githubusercontent.com/openstack/requirements/stable/newton/upper-constraints.txt'
    python_dependencies:
      - { name: PyMySQL }
      - { name: python-memcached }
      - { name: neutron-lbaas-dashboard }
      - { name: django_openstack_auth, version: '2.2.1.dev1' }
    system_dependencies:
      ubuntu:
        - apache2
        - libapache2-mod-wsgi
      rhel:
        - httpd
        - mod_wsgi
        - mod_proxy_uwsgi
  logs:
    - paths:
        - /var/log/apache2/access.log
      fields:
        type: openstack
        tags: horizon
    - paths:
        - /var/log/apache2/error.log
      fields:
        type: openstack
        tags: horizon
    - paths:
        - /var/log/apache2/other_vhosts_access.log
      fields:
        type: openstack
        tags: horizon
  logging:
    debug: False
    verbose: True
  monitoring:
    sensu_checks:
      check_http:
        criticality: 'critical'
  websso:
     choices:
       credentials: 'Keystone Authentication'
       oidc: 'OpenID Connect Authentication'
